- uses: burnett01/rsync-deployments@5.2
  with:
    switches: -avzr --delete
    path: docs/
    remote_path: /var/www/docs
    remote_host: ${{ secrets.SERVER_HOST }}
    remote_user: ${{ secrets.SERVER_USER }}
    remote_key: ${{ secrets.SERVER_SSH_KEY }}