name: Deploy Static Docs

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy `/docs` via SCP
    runs-on: ubuntu-22.04

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      SSH_HOST:        ${{ secrets.SSH_HOST }}
      SSH_USER:        ${{ secrets.SSH_USER }}
      SSH_TARGET_DIR:  ${{ secrets.SSH_TARGET_DIR }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Copy `/docs` via SCP
        run: |
          scp -r -i ~/.ssh/id_rsa docs/ "${SSH_USER}@${SSH_HOST}:${SSH_TARGET_DIR}/"